service: lambda-nodejs-vs-go

frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  architecture: arm64
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:GetObject'
  
custom:
  deploymentBucket:
    name: ${self:service}-deployment-bucket-${opt:stage, self:provider.stage}
    serverSideEncryption: AES256

package:
    individually: true

functions:
  hello:
    handler: node-lambda/handler.hello
    memorySize: 128
    package:
      include:
        - "node-lambda/**"
    environment:
      BUCKET: go-vs-nodejs-bucket
    events:
      - http:
          path: /hello-js
          method: GET
  helloGo:
    handler: bootstrap
    runtime: provided.al2
    architecture: arm64
    environment:
      BUCKET: go-vs-nodejs-bucket
    package:
      artifact: bin/go-lambda.zip
    memorySize: 128
    events:
      - http:
          path: /hello-go
          method: GET

